[command]
default=${APPS_ROOT_DIR}/build/local_build.py \
       -a lfric_atm \
       -c ${CORE_ROOT_DIR} \
       -w ${WORKING_DIR} \
       -j ${MAKE_THREADS} \
       -t ${TARGET} \
       -u ${LFRIC_TARGET_PLATFORM}

[file:$DESTINATION_DIRECTORY]
mode=mkdir

[file:$WORKING_DIR]
mode=mkdir
