[file:bin/tweak_iodef]
mode=auto
source=git:git@github.com:MetOffice/lfric_core.git::bin/tweak_iodef::core2.2

[template variables]
BUILD_LFRIC=true
CASE_SETUP=''
COMPILER='gnu'
EXPT_DT=120.0
EXPT_RESUB='P100D'
EXPT_RUNLEN='P10000D'
EXPT_START='20000101T0000Z'
EX_HOST='isambard3'
ISAMBARD3_SPACK_SETUP='../../env_lfric/working_dir/spack/share/spack/setup-env.sh'
ISAMBARD3_SPACK_ENV='lfric-apps-isambard'
ISAMBARD3_RUN_PARTITION='grace'
ISAMBARD3_SHARED_PARTITION='grace'
ISAMBARD3_MASS_PARTITION='grace'
ACTIVATE_ENV='../../env_lfric/activate.sh'
LFRIC_CPU='PT2H'
LFRIC_LEVS=''
LFRIC_RES='C48_MG'
PHYSICS_CONF=''
TOTAL_RANKS_REQ=108
VN='2.2'
GITHUB_TOKEN=''
GITHUB_USERNAME='x-access-token'
