# This file records CLI Options.
# Installed with:
#     * Cylc Rose: 1.7.0
#     * Rose     : 2.5.1
#     * Cylc     : 8.6.2

!opts=

[env]
# ROSE_ORIG_HOST set by cylc install.
ROSE_ORIG_HOST=login02.head.cm.i3.isambard.ac.uk

[template variables]
# ROSE_ORIG_HOST set by cylc install.
ROSE_ORIG_HOST=login02.head.cm.i3.isambard.ac.uk
